Repository KittyAdventure/Epliogue_BE, pull requests merged in 2025-03, with the labels that each got.

#55 feat : 네이버 API 로 가져온 책 데이터 DB 에 저장하는 기능 구현
  src/main/java/com/team1/epilogue/book/controller/BookController.java
  src/main/java/com/team1/epilogue/book/entity/Book.java
  src/main/java/com/team1/epilogue/book/repository/BookRepository.java
  src/main/java/com/team1/epilogue/book/service/BookService.java
  src/main/java/com/team1/epilogue/review/controller/ReviewController.java
  src/main/java/com/team1/epilogue/review/repository/ReviewRepository.java
  src/main/java/com/team1/epilogue/review/service/ReviewService.java
  src/test/java/com/team1/epilogue/book/service/BookServiceTest.java
  src/test/java/com/team1/epilogue/review/ReviewServiceTest.java
Labels: feat

#56 feat : Book 상세 정보 조회할때 같은작가의 다른 책들 함께 return 하게끔 구현
  src/main/java/com/team1/epilogue/book/dto/BookDetailResponse.java
  src/main/java/com/team1/epilogue/book/dto/SameAuthorBookTitleIsbn.java
  src/main/java/com/team1/epilogue/book/entity/Book.java
  src/main/java/com/team1/epilogue/book/repository/BookRepository.java
  src/main/java/com/team1/epilogue/book/service/BookService.java
Labels: feat

#57 refactor : Point 거래 관련 DB Lock 추가.
  src/main/java/com/team1/epilogue/auth/repository/MemberRepository.java
  src/main/java/com/team1/epilogue/transaction/service/TransactionService.java
Labels: reafactor

#59 Member와 Book 엔티티의 Rating 연관 관계 설정 및 별점 서비스 구현
  src/main/java/com/team1/epilogue/auth/entity/Member.java
  src/main/java/com/team1/epilogue/book/entity/Book.java
  src/main/java/com/team1/epilogue/rating/controller/RatingController.java
  src/main/java/com/team1/epilogue/rating/dto/RatingRequestDto.java
  src/main/java/com/team1/epilogue/rating/dto/RatingResponseDto.java
  src/main/java/com/team1/epilogue/rating/entity/Rating.java
  src/main/java/com/team1/epilogue/rating/exception/RatingNotFoundException.java
  src/main/java/com/team1/epilogue/rating/repository/RatingRepository.java
  src/main/java/com/team1/epilogue/rating/service/RatingService.java
  src/main/java/com/team1/epilogue/review/exception/ReviewExceptionHandler.java
  src/test/java/com/team1/epilogue/rating/RatingServiceTest.java
Labels: feat

#60 리뷰 API 리팩토링 및 불필요한 검증 삭제
  src/main/java/com/team1/epilogue/review/dto/ReviewResponseDto.java
  src/main/java/com/team1/epilogue/review/service/ReviewService.java
  src/test/java/com/team1/epilogue/review/ReviewServiceTest.java
Labels: reafactor

#58 feat: 회원 수정 및 일반/소셜 로그인 기능 추가
  .DS_Store
  .gitignore
  build.gradle
  docker-compose.yml
  gradlew
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/team1/.DS_Store
  src/main/java/com/team1/epilogue/.DS_Store
  src/main/java/com/team1/epilogue/EpilogueApplication.java
  src/main/java/com/team1/epilogue/auth/.DS_Store
  src/main/java/com/team1/epilogue/auth/controller/.DS_Store
  src/main/java/com/team1/epilogue/auth/controller/AuthController.java
  src/main/java/com/team1/epilogue/auth/controller/MemberController.java
  src/main/java/com/team1/epilogue/auth/controller/MemberWithdrawalController.java
  src/main/java/com/team1/epilogue/auth/dto/GeneralLoginRequest.java
  src/main/java/com/team1/epilogue/auth/dto/GoogleUserInfo.java
  src/main/java/com/team1/epilogue/auth/dto/KakaoUserInfo.java
  src/main/java/com/team1/epilogue/auth/dto/LoginResponse.java
  src/main/java/com/team1/epilogue/auth/dto/MemberResponse.java
  src/main/java/com/team1/epilogue/auth/dto/RegisterRequest.java
  src/main/java/com/team1/epilogue/auth/dto/SocialLoginRequest.java
  src/main/java/com/team1/epilogue/auth/dto/UpdateMemberRequest.java
  src/main/java/com/team1/epilogue/auth/dto/UserDto.java
  src/main/java/com/team1/epilogue/auth/exception/GoogleUserInfoException.java
  src/main/java/com/team1/epilogue/auth/exception/KakaoUserInfoException.java
  src/main/java/com/team1/epilogue/auth/exception/MemberNotFoundException.java
  src/main/java/com/team1/epilogue/auth/security/.DS_Store
  src/main/java/com/team1/epilogue/auth/security/CustomMemberDetails.java
  src/main/java/com/team1/epilogue/auth/security/CustomReactiveUserDetailsService.java
  src/main/java/com/team1/epilogue/auth/security/CustomUserDetailsService.java
  src/main/java/com/team1/epilogue/auth/security/JwtTokenProvider.java
  src/main/java/com/team1/epilogue/auth/service/.DS_Store
  src/main/java/com/team1/epilogue/auth/service/AuthService.java
  src/main/java/com/team1/epilogue/auth/service/AuthServiceImpl.java
  src/main/java/com/team1/epilogue/auth/service/GoogleAuthService.java
  src/main/java/com/team1/epilogue/auth/service/KakaoAuthService.java
  src/main/java/com/team1/epilogue/auth/service/MemberService.java
  src/main/java/com/team1/epilogue/config/SecurityConfig.java
  src/test/.DS_Store
  src/test/java/.DS_Store
  src/test/java/com/.DS_Store
  src/test/java/com/team1/.DS_Store
  src/test/java/com/team1/epilogue/.DS_Store
  src/test/java/com/team1/epilogue/auth/.DS_Store
  src/test/java/com/team1/epilogue/auth/controller/.DS_Store
  src/test/java/com/team1/epilogue/auth/controller/AuthControllerTest.java
  src/test/java/com/team1/epilogue/auth/controller/MemberControllerTest.java
  src/test/java/com/team1/epilogue/auth/controller/MemberWithdrawalControllerTest.java
  src/test/java/com/team1/epilogue/auth/service/.DS_Store
  src/test/java/com/team1/epilogue/auth/service/AuthServiceImplTest.java
  src/test/java/com/team1/epilogue/auth/service/MemberServiceTest.java
  src/test/java/com/team1/epilogue/auth/service/MemberWithdrawalServiceTest.java
Labels: feat

#62 feat : 댓글 작성기능 구현
  src/main/java/com/team1/epilogue/auth/domain/COMMENT_COLOR_ITEM.java
  src/main/java/com/team1/epilogue/auth/entity/Member.java
  src/main/java/com/team1/epilogue/comment/controller/CommentController.java
  src/main/java/com/team1/epilogue/comment/dto/CommentPostRequest.java
  src/main/java/com/team1/epilogue/comment/entity/Comment.java
  src/main/java/com/team1/epilogue/comment/repository/CommentRepository.java
  src/main/java/com/team1/epilogue/comment/service/CommentService.java
  src/test/java/com/team1/epilogue/comment/service/CommentServiceTest.java
Labels: feat

#63 feat : 댓글 수정기능 구현
  src/main/java/com/team1/epilogue/comment/controller/CommentController.java
  src/main/java/com/team1/epilogue/comment/dto/CommentUpdateRequest.java
  src/main/java/com/team1/epilogue/comment/exception/CommentExceptionHandler.java
  src/main/java/com/team1/epilogue/comment/exception/CommentNotFoundException.java
  src/main/java/com/team1/epilogue/comment/exception/UnauthorizedMemberException.java
  src/main/java/com/team1/epilogue/comment/service/CommentService.java
  src/test/java/com/team1/epilogue/comment/service/CommentServiceTest.java
Labels: feat

#73 feat : 오프라인 모임 생성, TestCode 작성
  src/main/java/com/team1/epilogue/gathering/controller/MeetingController.java
  src/main/java/com/team1/epilogue/gathering/dto/MeetingDto.java
  src/main/java/com/team1/epilogue/gathering/entity/Meeting.java
  src/main/java/com/team1/epilogue/gathering/repository/MeetingRepository.java
  src/main/java/com/team1/epilogue/gathering/service/MeetingService.java
  src/test/java/com/team1/epilogue/gathering/service/MeetingServiceTest.java
Labels: feat

#75 refactor : 카카오페이 api , 네이버 책검색 api 두가지 테스트코드 모두 작성완료
  src/test/java/com/team1/epilogue/book/client/NaverApiClientTest.java
  src/test/java/com/team1/epilogue/transaction/client/KakaoPayClientTest.java
Labels: reafactor

#74 Feat/ 인기 검색어 기능
  src/main/java/com/team1/epilogue/EpilogueApplication.java
  src/main/java/com/team1/epilogue/book/service/BookService.java
  src/main/java/com/team1/epilogue/config/SecurityConfig.java
  src/main/java/com/team1/epilogue/keyword/controller/KeyWordController.java
  src/main/java/com/team1/epilogue/keyword/service/KeyWordService.java
Labels: feat

#77 Feat/ 댓글 삭제 기능
  src/main/java/com/team1/epilogue/comment/controller/CommentController.java
  src/main/java/com/team1/epilogue/comment/service/CommentService.java
  src/test/java/com/team1/epilogue/comment/service/CommentServiceTest.java
Labels: feat

#82 Feat/인기 책 조회 기능
  src/main/java/com/team1/epilogue/EpilogueApplication.java
  src/main/java/com/team1/epilogue/book/repository/BookRepository.java
  src/main/java/com/team1/epilogue/book/service/BookService.java
  src/main/java/com/team1/epilogue/config/SecurityConfig.java
  src/main/java/com/team1/epilogue/trendingbook/controller/TrendingBookController.java
  src/main/java/com/team1/epilogue/trendingbook/entity/BookDetailHistory.java
  src/main/java/com/team1/epilogue/trendingbook/repository/TrendingBookRepository.java
  src/main/java/com/team1/epilogue/trendingbook/service/TrendingBookService.java
  src/test/java/com/team1/epilogue/trendingbook/service/TrendingBookServiceTest.java
Labels: feat

#84 refactor : return 타입 와일드카드 삭제,Map -> DTO로 return, Entity 내부 @Setter 삭제
  src/main/java/com/team1/epilogue/book/controller/BookController.java
  src/main/java/com/team1/epilogue/book/entity/Book.java
  src/main/java/com/team1/epilogue/comment/controller/CommentController.java
  src/main/java/com/team1/epilogue/comment/dto/MessageResponse.java
  src/main/java/com/team1/epilogue/comment/entity/Comment.java
  src/main/java/com/team1/epilogue/keyword/controller/KeyWordController.java
  src/main/java/com/team1/epilogue/transaction/controller/TransactionController.java
  src/main/java/com/team1/epilogue/transaction/entity/Transaction.java
Labels: reafactor

#81 리뷰 좋아요 기능 및 정렬 기준 추가
  src/main/java/com/team1/epilogue/review/controller/ReviewController.java
  src/main/java/com/team1/epilogue/review/dto/ReviewResponseDto.java
  src/main/java/com/team1/epilogue/review/entity/Review.java
  src/main/java/com/team1/epilogue/review/entity/ReviewLike.java
  src/main/java/com/team1/epilogue/review/exception/AlreadyLikedException.java
  src/main/java/com/team1/epilogue/review/exception/LikeNotFoundException.java
  src/main/java/com/team1/epilogue/review/exception/ReviewExceptionHandler.java
  src/main/java/com/team1/epilogue/review/repository/ReviewLikeRepository.java
  src/main/java/com/team1/epilogue/review/repository/ReviewRepository.java
  src/main/java/com/team1/epilogue/review/service/ReviewService.java
  src/test/java/com/team1/epilogue/review/ReviewServiceTest.java
Labels: feat

#85 feat : mypage 내부 "내 댓글 보기" 기능 추가
  src/main/java/com/team1/epilogue/comment/repository/CommentRepository.java
  src/main/java/com/team1/epilogue/mypage/controller/MyPageController.java
  src/main/java/com/team1/epilogue/mypage/dto/MyPageCommentsDetailResponse.java
  src/main/java/com/team1/epilogue/mypage/dto/MyPageCommentsResponse.java
  src/main/java/com/team1/epilogue/mypage/service/MyPageService.java
  src/test/java/com/team1/epilogue/mypage/service/MyPageServiceTest.java
Labels: feat

#95 Feat/review auth refactor
  src/main/java/com/team1/epilogue/review/controller/ReviewController.java
  src/main/java/com/team1/epilogue/review/service/ReviewService.java
Labels: reafactor

#88 feat : 마이페이지 내부 특정 회원의 리뷰 리스트 조회 기능 구현
  src/main/java/com/team1/epilogue/comment/service/CommentService.java
  src/main/java/com/team1/epilogue/config/SecurityConfig.java
  src/main/java/com/team1/epilogue/mypage/controller/MyPageController.java
  src/main/java/com/team1/epilogue/mypage/dto/MyPageReviewDetail.java
  src/main/java/com/team1/epilogue/mypage/dto/MyPageReviewsResponse.java
  src/main/java/com/team1/epilogue/mypage/service/MyPageService.java
  src/main/java/com/team1/epilogue/review/entity/Review.java
  src/main/java/com/team1/epilogue/review/repository/ReviewRepository.java
  src/test/java/com/team1/epilogue/mypage/service/MyPageServiceTest.java
Labels: feat

#91 refactor : authentication 사용하는 방법 수정
  src/main/java/com/team1/epilogue/comment/controller/CommentController.java
  src/main/java/com/team1/epilogue/comment/service/CommentService.java
  src/main/java/com/team1/epilogue/mypage/controller/MyPageController.java
  src/main/java/com/team1/epilogue/mypage/service/MyPageService.java
  src/test/java/com/team1/epilogue/comment/service/CommentServiceTest.java
  src/test/java/com/team1/epilogue/mypage/service/MyPageServiceTest.java
Labels: reafactor

#93 feat : 책 메인 페이지 응답하는 API 구현 완료
  .gitignore
  build.gradle
  src/main/java/com/team1/epilogue/book/controller/BookController.java
  src/main/java/com/team1/epilogue/book/dto/BookMainPageDetail.java
  src/main/java/com/team1/epilogue/book/dto/BookMainPageDto.java
  src/main/java/com/team1/epilogue/book/dto/BookSearchFilter.java
  src/main/java/com/team1/epilogue/book/entity/Book.java
  src/main/java/com/team1/epilogue/book/repository/BookRepository.java
  src/main/java/com/team1/epilogue/book/repository/CustomBookRepository.java
  src/main/java/com/team1/epilogue/book/repository/CustomBookRepositoryImpl.java
  src/main/java/com/team1/epilogue/book/service/BookService.java
  src/main/java/com/team1/epilogue/config/QueryDslConfig.java
  src/main/java/com/team1/epilogue/config/SecurityConfig.java
  src/test/java/com/team1/epilogue/book/service/BookServiceTest.java
Labels: feat

#94 Feat : 리뷰에 대한 댓글 조회하는 기능 구현
  src/main/java/com/team1/epilogue/comment/controller/CommentController.java
  src/main/java/com/team1/epilogue/comment/dto/CommentDetail.java
  src/main/java/com/team1/epilogue/comment/dto/CommentResponse.java
  src/main/java/com/team1/epilogue/comment/repository/CommentRepository.java
  src/main/java/com/team1/epilogue/comment/service/CommentService.java
  src/main/java/com/team1/epilogue/config/SecurityConfig.java
  src/test/java/com/team1/epilogue/comment/service/CommentServiceTest.java
Labels: feat

#98 feat : 컬렉션 기능 구현하였습니다.
  src/main/java/com/team1/epilogue/collection/controller/CollectionController.java
  src/main/java/com/team1/epilogue/collection/dto/CollectionDetail.java
  src/main/java/com/team1/epilogue/collection/dto/CollectionResponse.java
  src/main/java/com/team1/epilogue/collection/dto/StringResponse.java
  src/main/java/com/team1/epilogue/collection/entity/CollectionEntity.java
  src/main/java/com/team1/epilogue/collection/exception/AlreadyAddedCollectionException.java
  src/main/java/com/team1/epilogue/collection/exception/CollectionExceptionHandler.java
  src/main/java/com/team1/epilogue/collection/repository/CollectionRepository.java
  src/main/java/com/team1/epilogue/collection/service/CollectionService.java
  src/test/java/com/team1/epilogue/collection/service/CollectionServiceTest.java
Labels: feat

#99 feat: 댓글 좋아요 및 취소 API 추가
  src/main/java/com/team1/epilogue/comment/controller/CommentController.java
  src/main/java/com/team1/epilogue/comment/entity/Comment.java
  src/main/java/com/team1/epilogue/comment/entity/CommentLike.java
  src/main/java/com/team1/epilogue/comment/repository/CommentLikeRepository.java
  src/main/java/com/team1/epilogue/comment/repository/CommentRepository.java
  src/main/java/com/team1/epilogue/comment/service/CommentService.java
  src/test/java/com/team1/epilogue/comment/service/CommentServiceTest.java
Labels: feat

#101 fix : 채팅방 생성, 채팅방 참가, 채팅 내용 저장,전송을 동시에 바꿈, 테스트 코드 작성
  src/main/java/com/team1/epilogue/Handler/ChatWebSocketHandler.java
  src/main/java/com/team1/epilogue/chat/controller/ChatController.java
  src/main/java/com/team1/epilogue/chat/controller/ChatRestController.java
  src/main/java/com/team1/epilogue/chat/controller/ParticipationController.java
  src/main/java/com/team1/epilogue/chat/dto/ChatRoomDto.java
  src/main/java/com/team1/epilogue/chat/entity/ChatRoom.java
  src/main/java/com/team1/epilogue/chat/repository/ChatRoomRepository.java
  src/main/java/com/team1/epilogue/chat/service/ChatRoomService.java
  src/main/java/com/team1/epilogue/chat/service/ParticipationService.java
  src/main/java/com/team1/epilogue/config/MongoConfig.java
  src/test/java/com/team1/epilogue/chat/controller/ChatControllerTest.java
  src/test/java/com/team1/epilogue/chat/service/ChatMessageServiceTest.java
  src/test/java/com/team1/epilogue/chat/service/ChatRoomServiceTest.java
  src/test/java/com/team1/epilogue/chat/service/ParticipationServiceTest.java
Labels: bug, wontfix

#105 refactor: 별점 Authentication에서 CustomMemberDetails 사용하도록 변경
  src/main/java/com/team1/epilogue/rating/controller/RatingController.java
  src/main/java/com/team1/epilogue/rating/service/RatingService.java
  src/main/java/com/team1/epilogue/review/entity/Review.java
  src/test/java/com/team1/epilogue/rating/RatingServiceTest.java
  src/test/java/com/team1/epilogue/review/ReviewServiceTest.java
Labels: reafactor

#107 feat : 모임 조회 ,테스트 코드 작성
  src/main/java/com/team1/epilogue/gathering/controller/MeetingController.java
  src/main/java/com/team1/epilogue/gathering/repository/MeetingRepository.java
  src/main/java/com/team1/epilogue/gathering/service/MeetingService.java
  src/test/java/com/team1/epilogue/gathering/service/MeetingServiceTest.java
Labels: feat

#109 feat: 미팅 참가,떠나기,조회,조회카운터 구현,테스트 코드 미팅 참가테스트, 떠나기 구현
  src/main/java/com/team1/epilogue/gathering/controller/MeetingController.java
  src/main/java/com/team1/epilogue/gathering/dto/JoinMeetingRequestDto.java
  src/main/java/com/team1/epilogue/gathering/dto/JoinMeetingResponseDto.java
  src/main/java/com/team1/epilogue/gathering/entity/JoinMeeting.java
  src/main/java/com/team1/epilogue/gathering/repository/JoinMeetingRepository.java
  src/main/java/com/team1/epilogue/gathering/service/JoinMeetingService.java
  src/test/java/com/team1/epilogue/gathering/service/JoinMeetingServiceTest.java
Labels: feat

#104 Feat/offline delete
  src/main/java/com/team1/epilogue/common/entity/BaseEntity.java
  src/main/java/com/team1/epilogue/config/WebSocketConfig.java
  src/main/java/com/team1/epilogue/gathering/controller/MeetingController.java
  src/main/java/com/team1/epilogue/gathering/dto/MeetingDto.java
  src/main/java/com/team1/epilogue/gathering/service/MeetingService.java
  src/test/java/com/team1/epilogue/gathering/service/MeetingServiceTest.java
Labels: feat

#113 feat: 책 상세 페이지에서의 팔로우 후기
  src/main/java/com/team1/epilogue/follow/repository/FollowRepository.java
  src/main/java/com/team1/epilogue/review/controller/ReviewController.java
  src/main/java/com/team1/epilogue/review/repository/ReviewRepository.java
  src/main/java/com/team1/epilogue/review/service/ReviewService.java
  src/test/java/com/team1/epilogue/review/ReviewServiceTest.java
Labels: feat

#114 feat: 회원 아이디 검색, 테스트코드 작성
  src/main/java/com/team1/epilogue/auth/controller/MemberController.java
  src/main/java/com/team1/epilogue/auth/repository/CustomBookRepositoryImpl.java
  src/main/java/com/team1/epilogue/auth/repository/CustomMemberRepository.java
  src/main/java/com/team1/epilogue/auth/service/MemberService.java
  src/main/java/com/team1/epilogue/config/SecurityConfig.java
  src/test/java/com/team1/epilogue/auth/service/MemberServiceTest.java
Labels: feat

#117 feat: 별점 평균(avgRating) 기능 추가
  src/main/java/com/team1/epilogue/book/dto/BookDetailResponse.java
  src/main/java/com/team1/epilogue/book/entity/Book.java
  src/main/java/com/team1/epilogue/book/repository/BookRepository.java
  src/main/java/com/team1/epilogue/book/service/BookService.java
  src/main/java/com/team1/epilogue/rating/repository/RatingRepository.java
  src/main/java/com/team1/epilogue/rating/service/RatingService.java
Labels: feat

#119 아이템 관련 기능 구현
  src/main/java/com/team1/epilogue/common/entity/BaseEntity.java
  src/main/java/com/team1/epilogue/config/SecurityConfig.java
  src/main/java/com/team1/epilogue/transaction/controller/TransactionController.java
  src/main/java/com/team1/epilogue/transaction/dto/BoughtItemDetail.java
  src/main/java/com/team1/epilogue/transaction/dto/BoughtItemList.java
  src/main/java/com/team1/epilogue/transaction/dto/ItemList.java
  src/main/java/com/team1/epilogue/transaction/dto/ItemListDetail.java
  src/main/java/com/team1/epilogue/transaction/entity/Item.java
  src/main/java/com/team1/epilogue/transaction/entity/ItemBuyHistory.java
  src/main/java/com/team1/epilogue/transaction/entity/NotEnoughPointException.java
  src/main/java/com/team1/epilogue/transaction/exception/AlreadyBoughtItemException.java
  src/main/java/com/team1/epilogue/transaction/exception/ItemNotFoundException.java
  src/main/java/com/team1/epilogue/transaction/exception/TransactionExceptionHandler.java
  src/main/java/com/team1/epilogue/transaction/repository/ItemBuyHistoryRepository.java
  src/main/java/com/team1/epilogue/transaction/repository/ItemRepository.java
  src/main/java/com/team1/epilogue/transaction/repository/TransactionRepository.java
  src/main/java/com/team1/epilogue/transaction/service/TransactionService.java
  src/test/java/com/team1/epilogue/transaction/service/TransactionServiceTest.java
Labels: feat

#123 feat: ReviewResponseDto에 책 커버 이미지 URL 추가
  src/main/java/com/team1/epilogue/review/dto/ReviewResponseDto.java
Labels: feat

#126 feat : 마이페이지 내부 유저 정보주는 메서드 추가
  src/main/java/com/team1/epilogue/collection/repository/CollectionRepository.java
  src/main/java/com/team1/epilogue/comment/repository/CommentRepository.java
  src/main/java/com/team1/epilogue/config/SecurityConfig.java
  src/main/java/com/team1/epilogue/follow/repository/FollowRepository.java
  src/main/java/com/team1/epilogue/gathering/repository/JoinMeetingRepository.java
  src/main/java/com/team1/epilogue/mypage/controller/MyPageController.java
  src/main/java/com/team1/epilogue/mypage/dto/MyPageUserInfo.java
  src/main/java/com/team1/epilogue/mypage/service/MyPageService.java
  src/main/java/com/team1/epilogue/review/repository/ReviewRepository.java
Labels: feat

#129 refactor: review rating 중복 메서드 정리 및 테스트 코드 수정
  src/main/java/com/team1/epilogue/rating/service/RatingService.java
  src/main/java/com/team1/epilogue/review/entity/Review.java
  src/main/java/com/team1/epilogue/review/service/ReviewService.java
  src/test/java/com/team1/epilogue/chat/service/ChatRoomServiceTest.java
  src/test/java/com/team1/epilogue/review/ReviewServiceTest.java
Labels: reafactor

#132 feat: 책 상세 응답에 내 별점(myRating) 추가 및 리뷰 목록에 좋아요 여부 포함
  src/main/java/com/team1/epilogue/book/dto/BookDetailResponse.java
  src/main/java/com/team1/epilogue/book/service/BookService.java
  src/main/java/com/team1/epilogue/review/controller/ReviewController.java
  src/main/java/com/team1/epilogue/review/dto/ReviewResponseDto.java
  src/main/java/com/team1/epilogue/review/repository/ReviewLikeRepository.java
  src/main/java/com/team1/epilogue/review/service/ReviewService.java
  src/test/java/com/team1/epilogue/chat/service/ChatRoomServiceTest.java
  src/test/java/com/team1/epilogue/review/ReviewServiceTest.java
Labels: feat

#133 feat: 메인화면 - 최신순 리뷰 조회 시 로그인한 사용자의 좋아요 여부(liked) 반영
  src/main/java/com/team1/epilogue/review/controller/ReviewController.java
  src/main/java/com/team1/epilogue/review/service/ReviewService.java
Labels: feat
